### ISSUE TITLE
SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A

### ISSUE THREAD

**Issue by stinnux** [lehn-etracker/vagrant-proxmox#3]
I have a Proxmox-Server that is using a valid let's encrypt certificate.

When trying to connect using vagrant-proxmox i often get the above mentioned error on the first try. 

Trying again immediately afterwards is successful.

**Comment by lehn-etracker** [comment]
Do you connect every time to the same node? Maybe one node has not yet the new certificate. See https://pve.proxmox.com/wiki/HTTPS_Certificate_Configuration_(Version_4.x_and_newer)

**Comment by stinnux** [comment]
It's the Same Node, i currently have only one for testing.

**Comment by lehn-etracker** [comment]
Issue closed due no response from reporter
